### ISSUE TITLE
cannot find Swift declaration for this class

### ISSUE THREAD

**Issue by manoharsinghrawat-cedcoss** [cashfree/ios-sdk#21]
I am getting this error for classes declared in framework files

**Comment by basilcf** [comment]
Are you using Simulator or physical ios device in your Xcode project ?
Is the project Swift version 4.2 ?

If you're still facing issue, please give us some more information.

**Comment by manoharsinghrawat-cedcoss** [comment]
Error: No payment token received. Please try again sending new request for token (initPayment).
I am getting this error
